### ISSUE TITLE
I met this error when run main.py

### ISSUE THREAD

**Issue by bemoregt** [errollw/EyeTab#1]
Hi, @errollw 

I met this error when run main.py

kraken-2:EyeTab_Python dti$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import gaze_system as gaze_system
  File "/Users/dti/EyeTab/EyeTab_Python/gaze_system.py", line 4, in <module>
    import draw_utils
  File "/Users/dti/EyeTab/EyeTab_Python/draw_utils.py", line 5
    def draw_cross(bgr_img, (x, y), color=(255, 255, 255), width=2, thickness=1):
                            ^
SyntaxError: invalid syntax

What's wrong with me?

Thanks in advance~

**Comment by yutao007** [comment]
我也遇到同样的问题，楼主是否已经解决了？

**Comment by LingYu-Chu** [comment]
Hello, 

I met the same error.

**Comment by alessandrobruno10** [comment]
I think that you need to replace def draw_cross(bgr_img, (x, y), color=(255, 255, 255), width=2, thickness=1):
with 
def draw_cross(bgr_img, x, y, color=(255, 255, 255), width=2, thickness=1):
